
apiVersion: v1
kind: Service
metadata:
  name: reportingdashboardwar
  labels:
    app: reportingdashboardwar
spec:
  ports:
    - port: 9080
  selector:
    app: reportingdashboardwar
  type: NodePort

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: reportingdashboardwar
  name: reportingdashboardwar
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: reportingdashboardwar
    spec:
      containers:
      - image: mycluster.icp:8500/default/reportingdashboardwar:latest
        name: reportingdashboardwar
        ports:
        - containerPort: 9080
          protocol: TCP
